In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
df_whole = pd.read_csv("/Users/shabbir.hasan/Documents/Hasan/Anaconda_rep/Kaggle/New_York_City_Taxi_Fare_Prediction/train.csv")

In [36]:
test_kaggle = pd.read_csv("/Users/shabbir.hasan/Documents/Hasan/Anaconda_rep/Kaggle/New_York_City_Taxi_Fare_Prediction/test.csv")

###  Creating test pipline 

In [ ]:
# splitting data randomly (not using whole data for now)
train, test = train_test_split(df_whole, test_size=0.7)

In [ ]:
test.shape
train.shape

In [ ]:
#removing index
train = train.reset_index()

train =  train.drop('index', 1)

In [ ]:
# splice key
#train.key = train.key.astype(str).str[14:21]

In [ ]:
train.head(100)

In [9]:
train.isnull().values.any()

True

In [10]:
train = train.dropna() 

In [11]:
#Splitting into test and trin
# splitting data randomly (not using whole data for now, taking very small chunk)
#train, test = train_test_split(train, test_size=0.25)

In [12]:
#train.shape
#test.shape

In [13]:
test.head()

key  fare_amount          pickup_datetime  \
53178670  2009-01-29 23:25:00.000000124         13.7  2009-01-29 23:25:00 UTC   
2017860     2015-01-02 16:00:19.0000002          8.5  2015-01-02 16:00:19 UTC   
22480335    2010-07-29 04:49:47.0000001          8.9  2010-07-29 04:49:47 UTC   
14578613  2009-04-02 19:09:00.000000272          9.3  2009-04-02 19:09:00 UTC   
41626416    2014-11-09 19:52:31.0000001          6.0  2014-11-09 19:52:31 UTC   

          pickup_longitude  pickup_latitude  dropoff_longitude  \
53178670        -73.994897        40.755210         -73.985328   
2017860         -73.992386        40.737247         -74.008690   
22480335        -73.992087        40.724852         -73.964681   
14578613        -73.959097        40.774975         -73.966307   
41626416        -73.989604        40.747382         -73.979654   

          dropoff_latitude  passenger_count  
53178670         40.722818                1  
2017860          40.731537                1  
22480335         40.763956                1  
14578613         40.803112                1  
41626416         40.749716                1

In [14]:
#removing key and pickup_datetime
train = train.drop('key', 1)
train = train.drop('pickup_datetime', 1)

In [15]:
#removing key and pickup_datetime
test = test.drop('key', 1)
test = test.drop('pickup_datetime', 1)

In [16]:
# Split the data into training/testing sets
train_label = train.fare_amount
train_data = train.drop('fare_amount', 1)

In [17]:
test = test.dropna() 

In [18]:
test.head()
test.shape

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
53178670         13.7        -73.994897        40.755210         -73.985328   
2017860           8.5        -73.992386        40.737247         -74.008690   
22480335          8.9        -73.992087        40.724852         -73.964681   
14578613          9.3        -73.959097        40.774975         -73.966307   
41626416          6.0        -73.989604        40.747382         -73.979654   

          dropoff_latitude  passenger_count  
53178670         40.722818                1  
2017860          40.731537                1  
22480335         40.763956                1  
14578613         40.803112                1  
41626416         40.749716                1

(38796437, 6)

In [19]:
test_label = test.fare_amount
test_data = test.drop('fare_amount', 1)

####  creating test model and predicting on base of it

In [20]:
# Create linear regression object
regr = linear_model.LinearRegression()

In [21]:
# Train the model using the training sets
regr.fit(train_data, train_label)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [22]:
# Make predictions using the testing set
test_label_pred = regr.predict(test_data)

In [23]:
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(test_label, test_label_pred))

Coefficients: 
 [ 0.00225295 -0.00167121  0.00444721 -0.00194422  0.09473036]
Mean squared error: 571.31


In [24]:
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(test_label, test_label_pred))

Variance score: 0.00


####  predicting on given test data

In [25]:
test_kaggle.head()

key          pickup_datetime  pickup_longitude  \
0  2015-01-27 13:08:24.0000002  2015-01-27 13:08:24 UTC        -73.973320   
1  2015-01-27 13:08:24.0000003  2015-01-27 13:08:24 UTC        -73.986862   
2  2011-10-08 11:53:44.0000002  2011-10-08 11:53:44 UTC        -73.982524   
3  2012-12-01 21:12:12.0000002  2012-12-01 21:12:12 UTC        -73.981160   
4  2012-12-01 21:12:12.0000003  2012-12-01 21:12:12 UTC        -73.966046   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0        40.763805         -73.981430         40.743835                1  
1        40.719383         -73.998886         40.739201                1  
2        40.751260         -73.979654         40.746139                1  
3        40.767807         -73.990448         40.751635                1  
4        40.789775         -73.988565         40.744427                1

In [26]:
test_kaggle.key[8][14:21]

'10:20.0'

In [27]:
# ?test_kaggle.key = test_kaggle.key.apply(lambda x: x[14:21])

In [30]:
# kaggle_key = test_kaggle.key
test_kaggle = test_kaggle.drop('key', 1)
test_kaggle = test_kaggle.drop('pickup_datetime', 1)

KeyError: "['pickup_datetime'] not found in axis"

In [31]:
# Make predictions using the testing set
test_kagle_label_pred = regr.predict(test_kaggle)

In [32]:
#checking values
test_kagle_label_pred[1:5]

array([11.26550306, 11.2655316 , 11.26544833, 11.26546805])

In [33]:
#rounding of to two decimal
import numpy as np
test_kagle_label_pred = np.round(test_kagle_label_pred, decimals=2)

In [34]:
#checking values
test_kagle_label_pred[1:5]

array([11.27, 11.27, 11.27, 11.27])

In [35]:
submission = pd.DataFrame()

In [37]:
submission.key = pd.DataFrame(test_kaggle.key)
submission.fare_amount = pd.DataFrame(test_kagle_label_pred)

C:\Users\shabbir.hasan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.
C:\Users\shabbir.hasan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


In [38]:
col_names =  ['key', 'fare_amount']
submission  = pd.DataFrame(columns = col_names)


In [39]:
submission.head()

Empty DataFrame
Columns: [key, fare_amount]
Index: []

In [40]:
submission.key = (test_kaggle.key)
submission.fare_amount = test_kagle_label_pred

In [41]:
submission.head()

key  fare_amount
0  2015-01-27 13:08:24.0000002        11.27
1  2015-01-27 13:08:24.0000003        11.27
2  2011-10-08 11:53:44.0000002        11.27
3  2012-12-01 21:12:12.0000002        11.27
4  2012-12-01 21:12:12.0000003        11.27

In [42]:
submission.to_csv('submission_2.csv', index=False )

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [ ]:
train.isnull().values.any()

In [ ]:
reg = RandomForestRegressor(n_estimators=1000, max_depth=3,
                              random_state=0)

In [ ]:
reg.fit(train_data, train_label)

In [ ]:
RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [ ]:
print(clf.feature_importances_)

In [ ]:
test_label_pred = reg.predict(test_data)

In [ ]:
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(test_label, test_label_pred))