In [1]:
!pip install gym

  Running setup.py bdist_wheel for gym: started
  Running setup.py bdist_wheel for gym: finished with status 'done'
  Stored in directory: C:\Users\shabbir.hasan\AppData\Local\pip\Cache\wheels\6c\3a\0e\b86dee98876bb56cdb482cc1f72201035e46d1baf69d10d028
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: C:\Users\shabbir.hasan\AppData\Local\pip\Cache\wheels\0c\61\d2\d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built gym future


twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [1]:
import gym

In [2]:
#env = gym.make('CartPole-v0')
env = gym.make('MountainCar-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [10]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[ 0.03332502  0.01485969 -0.00449222  0.00648289]
[ 0.03362222  0.21004577 -0.00436256 -0.287614  ]
[ 0.03782313  0.40522967 -0.01011484 -0.58166964]
[ 0.04592772  0.21025089 -0.02174824 -0.29219015]
[ 0.05013274  0.40567607 -0.02759204 -0.59165207]
[ 0.05824626  0.60117322 -0.03942508 -0.89289721]
[ 0.07026973  0.7968071  -0.05728302 -1.19770797]
[ 0.08620587  0.99262169 -0.08123718 -1.50778009]
[ 0.1060583   1.18862916 -0.11139279 -1.82467913]
[ 0.12983089  1.38479701 -0.14788637 -2.149789  ]
[ 0.15752683  1.58103296 -0.19088215 -2.48425025]
Episode finished after 11 timesteps
[-0.01742065  0.04000558  0.04943026 -0.04047008]
[-0.01662053 -0.15578906  0.04862085  0.26738974]
[-0.01973632  0.03860648  0.05396865 -0.00957008]
[-0.01896419 -0.15724625  0.05377725  0.29964037]
[-0.02210911 -0.35309185  0.05977006  0.60878697]
[-0.02917095 -0.5489962   0.07194579  0.9196807 ]
[-0.04015087 -0.74501298  0.09033941  1.23407904]
[-0.05505113 -0.94117262  0.11502099  1.55364233]
[-0.07387458 -

[-0.02695624  0.02367361  0.02887809  0.06136502]
[-0.02648277 -0.17185023  0.03010539  0.36301747]
[-0.02991977 -0.36738684  0.03736574  0.66503913]
[-0.03726751 -0.17280402  0.05066652  0.38435161]
[-0.04072359 -0.36860731  0.05835355  0.69256923]
[-0.04809573 -0.1743414   0.07220494  0.41881255]
[-0.05158256  0.01968708  0.08058119  0.149738  ]
[-0.05118882 -0.17649076  0.08357595  0.46671513]
[-0.05471863 -0.37268795  0.09291025  0.78452644]
[-0.06217239 -0.17895712  0.10860078  0.52245988]
[-0.06575154 -0.3754266   0.11904998  0.84729382]
[-0.07326007 -0.18211226  0.13599586  0.59429282]
[-0.07690231 -0.37884931  0.14788171  0.92653328]
[-0.0844793  -0.18600036  0.16641238  0.68373609]
[-0.08819931 -0.38299404  0.1800871   1.02384425]
[-0.09585919 -0.19066762  0.20056398  0.79267995]
Episode finished after 18 timesteps
[-0.01197533 -0.03020679 -0.03114114  0.02352641]
[-0.01257946  0.16534759 -0.03067062 -0.27881696]
[-0.00927251 -0.0293237  -0.03624696  0.0040369 ]
[-0.00985899 -

[-0.09617553 -0.15252323  0.12030961  0.42296605]
[-0.09922599 -0.34912583  0.12876894  0.751024  ]
[-0.10620851 -0.15599264  0.14378942  0.50147624]
[-0.10932836  0.03684091  0.15381894  0.25733953]
[-0.10859154  0.22947053  0.15896573  0.01685125]
[-0.10400213  0.42199794  0.15930276 -0.22175931]
[-0.09556217  0.61452683  0.15486757 -0.46025882]
[-0.08327164  0.80715962  0.14566239 -0.70040056]
[-0.06712845  0.99999418  0.13165438 -0.94391576]
[-0.04712856  0.8033679   0.11277607 -0.61293405]
[-0.0310612   0.6068656   0.10051739 -0.28696708]
[-0.01892389  0.41046455  0.09477804  0.03564983]
[-0.0107146   0.21412025  0.09549104  0.35666751]
[-0.0064322   0.40776405  0.10262439  0.09555683]
[ 0.00172308  0.60127684  0.10453553 -0.16306654]
[0.01374862 0.40482581 0.1012742  0.16067891]
[ 0.02184514  0.59836305  0.10448778 -0.09841572]
[0.0338124  0.40191083 0.10251946 0.22531901]
[0.04185062 0.20548448 0.10702584 0.54849948]
[0.04596031 0.39895304 0.11799583 0.29136269]
[0.05393937 0.20

In [8]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)

Discrete(2)


In [4]:
#> Discrete(2)
print(env.observation_space)

Box(4,)


In [5]:
print(env.observation_space.high)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]


In [6]:
print(env.observation_space.low)

[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [7]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

In [9]:
import numpy as np
import sys
from six import StringIO, b

from gym import utils
from gym.envs.toy_text import discrete

LEFT = 0
DOWN = 1
RIGHT = 2
UP = 3

MAPS = {
    "4x4": [
        "SFFF",
        "FHFH",
        "FFFH",
        "HFFG"
    ],
    "8x8": [
        "SFFFFFFF",
        "FFFFFFFF",
        "FFFHFFFF",
        "FFFFFHFF",
        "FFFHFFFF",
        "FHHFFFHF",
        "FHFFHFHF",
        "FFFHFFFG"
    ],
}

class FrozenLakeEnv(discrete.DiscreteEnv):
    """
    Winter is here. You and your friends were tossing around a frisbee at the park
    when you made a wild throw that left the frisbee out in the middle of the lake.
    The water is mostly frozen, but there are a few holes where the ice has melted.
    If you step into one of those holes, you'll fall into the freezing water.
    At this time, there's an international frisbee shortage, so it's absolutely imperative that
    you navigate across the lake and retrieve the disc.
    However, the ice is slippery, so you won't always move in the direction you intend.
    The surface is described using a grid like the following
        SFFF
        FHFH
        FFFH
        HFFG
    S : starting point, safe
    F : frozen surface, safe
    H : hole, fall to your doom
    G : goal, where the frisbee is located
    The episode ends when you reach the goal or fall in a hole.
    You receive a reward of 1 if you reach the goal, and zero otherwise.
    """

    metadata = {'render.modes': ['human', 'ansi']}

    def __init__(self, desc=None, map_name="4x4",is_slippery=True):
        if desc is None and map_name is None:
            raise ValueError('Must provide either desc or map_name')
        elif desc is None:
            desc = MAPS[map_name]
        self.desc = desc = np.asarray(desc,dtype='c')
        self.nrow, self.ncol = nrow, ncol = desc.shape
        self.reward_range = (0, 1)

        nA = 4
        nS = nrow * ncol

        isd = np.array(desc == b'S').astype('float64').ravel()
        isd /= isd.sum()

        P = {s : {a : [] for a in range(nA)} for s in range(nS)}

        def to_s(row, col):
            return row*ncol + col
        
        def inc(row, col, a):
            if a==0: # left
                col = max(col-1,0)
            elif a==1: # down
                row = min(row+1,nrow-1)
            elif a==2: # right
                col = min(col+1,ncol-1)
            elif a==3: # up
                row = max(row-1,0)
            return (row, col)

        for row in range(nrow):
            for col in range(ncol):
                s = to_s(row, col)
                for a in range(4):
                    li = P[s][a]
                    letter = desc[row, col]
                    if letter in b'GH':
                        li.append((1.0, s, 0, True))
                    else:
                        if is_slippery:
                            for b in [(a-1)%4, a, (a+1)%4]:
                                newrow, newcol = inc(row, col, b)
                                newstate = to_s(newrow, newcol)
                                newletter = desc[newrow, newcol]
                                done = bytes(newletter) in b'GH'
                                rew = float(newletter == b'G')
                                li.append((1.0/3.0, newstate, rew, done))
                        else:
                            newrow, newcol = inc(row, col, a)
                            newstate = to_s(newrow, newcol)
                            newletter = desc[newrow, newcol]
                            done = bytes(newletter) in b'GH'
                            rew = float(newletter == b'G')
                            li.append((1.0, newstate, rew, done))

        super(FrozenLakeEnv, self).__init__(nS, nA, P, isd)

    def render(self, mode='human'):
        outfile = StringIO() if mode == 'ansi' else sys.stdout

        row, col = self.s // self.ncol, self.s % self.ncol
        desc = self.desc.tolist()
        desc = [[c.decode('utf-8') for c in line] for line in desc]
        desc[row][col] = utils.colorize(desc[row][col], "red", highlight=True)
        if self.lastaction is not None:
            outfile.write("  ({})\n".format(["Left","Down","Right","Up"][self.lastaction]))
        else:
            outfile.write("\n")
        outfile.write("\n".join(''.join(line) for line in desc)+"\n")

        if mode != 'human':
            return outfile